baraban/baraban/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('main.urls', namespace='main')),
]

baraban/main/urls.py
from django.urls import include, path
from .views import index_view, create_post_view, comments_view, delete_post_view, delete_comment_view

app_name = "main"

urlpatterns = [
    path("", index_view, name="index"),
    path("create", create_post_view, name="create_post"),
    path("post/<int:pk>/", comments_view, name="comments"),
    path("post/<int:pk>/delete", delete_post_view, name="delete_post"),
    path("post/<int:pk>/delete_comment", delete_comment_view, name="delete_comment")
]

baraban/user/urls.py
from django.urls import include, path
from .views import index_view, login_view, logout_view, register_view, password_change_view, password_reset_view
from django.contrib.auth.models import User
from django.http import request

app_name = "user"

urlpatterns = [
    path("", index_view, name="index"),
    path("<int:pk>", index_view, name="index"),
    path("login", login_view.as_view(), name="login"),
    path("logout",logout_view , name="logout"),
    path("register", register_view, name="register"),
    path("password_change", password_change_view.as_view(), name="password_change"),
    path("password_reset", password_reset_view.as_view(), name="password_reset")
]

baraban/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    topic = models.CharField(max_length=60, unique=True)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.topic

    def __repr__(self):
        return f"{self.topic}, {self.pub_date}, {self.creator}"


class Comment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"comment by {self.creator}"




    

baraban/user/models.py
from django.db import models
from django.contrib.auth.models import User

baraban/main/forms.py
from django import forms
from .models import Post

class PostForm(forms.Form):
    topic =  forms.CharField(max_length=60)
    content = forms.CharField(widget=forms.Textarea)

class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, label="Add your comment", min_length=2)
    

baraban/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label="E-mail")
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

baraban/main/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.models import User


# Create your views here.
def index_view(request):
    return render(request, "main/index.html", {"posts":Post.objects.all()})

@login_required
def create_post_view(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = Post(topic=request.POST["topic"], content=request.POST["content"], creator=request.user)
            new_post.save()
            return redirect("main:index")
    else:
        form = PostForm()
    return render(request, "main/add_post.html", {"form":form})

@login_required
def delete_post_view(request, pk):
    post = get_object_or_404(Post,pk=pk)
    if post.creator == request.user:
        post.delete()
        return redirect("main:index")
    else:
        return HttpResponse("Error")

@login_required
def comments_view(request, pk):
    post = get_object_or_404(Post,pk=pk)
    comments = post.comments.all()
    if request.method == "POST":
            new_comment = Comment(post=post, content=request.POST["content"], creator=request.user)
            new_comment.save()
            return redirect("main:comments", pk)
    else:
        form = CommentForm()
    return render(request, "main/comments.html", {"form":form, "post":post, "comments":comments})

@login_required
def delete_comment_view(request, pk):
    comment = get_object_or_404(Comment,pk=pk)
    if comment.creator == request.user:
        comment.delete()
    return redirect("main:index") 

baraban/user/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


@login_required
def index_view(request, pk=None):
    if pk is None and request.user.is_authenticated:
        pk = request.user.pk
    user = get_object_or_404(User, pk=pk)
    return render(request, "user/index.html", {"user":user})

def register_view(request):
    form = UserRegisterForm()
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("user:login")
    return render(request, "user/form.html", {"form":form})

@login_required
def logout_view(request):
    logout(request)
    return redirect("user:login")

class login_view(LoginView):
    template_name = "user/login.html"

class password_change_view(PasswordChangeView):
    template_name = "user/form.html"
    success_url = "/"
    

class password_reset_view(PasswordResetView):
    template_name = "user/form.html"
    success_url = "/"
    
             

baraban/main/templates/main/add_post.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{u}}
<form method="POST" class="form-group">
    {% csrf_token %}
    {{form|crispy}}
<input type="submit" class="btn btn-success">
</form>
{% endblock %}

baraban/main/templates/main/base.html
<!DOCTYPE html>
<html>

<head>
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark mb-2">
    <a class="navbar-brand" href="{% url 'main:index' %}">Main Page</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:index' %}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:create_post' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Register</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

</body>

</html>

baraban/main/templates/main/comments.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="col-8 mx-auto ">
        <div class="border mb-3">
            <h3 class="mb-0 px-2 py-1">{{post.topic}}</h3>
            <div class="px-2 pb-1 mb-1 text-muted">{{post.pub_date}}</div>
            <p class="mb-auto p-2">{{post.content}}</p>
            {% if user == post.creator%}
            Your post
            <a href="{% url 'main:delete_post' post.pk %}" >delete</a>
            {% else %}
            <a href="{% url 'user:index' post.creator.pk %}" class="p-2">{{post.creator}}</a>
            {% endif %}
        </div>

        {% for comment in comments %}

        <div class="border mb-3">
            <h5 class="mb-0 px-2 py-1"><a href="{% url 'user:index' comment.creator.pk %}">{{comment.creator}}</a></h5>
            <div class="px-2 mb-1 text-muted">{{comment.pub_date}}</div>
            <p class="mb-auto px-2 py-1"> {{comment.content}}</p>
            {% if user == post.creator or user == comment.creator%}
            <a href="{% url 'main:delete_comment' comment.pk %}" >delete</a>
            {% endif %}
        </div>

        {% endfor %}



        <form method="POST" class="form-group">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-success">
        </form>
    </div>

</div>

{% endblock %}

baraban/main/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}

<div class="container">
    
    {% for post in posts %}
    <div class="border col-8 mx-auto mb-3">

    <h3 class="mb-0 px-2 py-1"><a class="text-dark" href="{% url 'main:comments' post.pk %}">{{post.topic}}</a></h3>
    <div class="px-2 pb-1 mb-1 text-muted">{{post.pub_date}}</div>
    <p class="mb-auto p-2">{{post.content}}</p>
    <a href="{% url 'user:index' post.creator.pk %}" class="p-2">{{post.creator}}</a>
    </div>
{% endfor %}

</div>

{% endblock %}

baraban/main/templates/main/post.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{u}}
<form method="POST" class="form-group">
    {% csrf_token %}
    {{form|crispy}}
<input type="submit" class="btn btn-success">
</form>
{% endblock %}

baraban/user/templates/user/form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="form-group">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-success">Submit</button>
	</form>
{% endblock %}

baraban/user/templates/user/index.html
{% extends "main/base.html" %}
{% block content %}
ID: {{user.pk}}<br/>
Username: {{user.username}}<br/>
<a href="{% url 'user:password_change' %}">Change Password</a>
{% endblock %}

baraban/user/templates/user/login.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="form-group">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-success">Submit</button>
	</form>
	<a href="{% url 'user:password_reset' %}">Password reminder</a>
{% endblock %}

baraban/user/templates/user/register.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="form-group">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-success">Register</button>
	</form>
{% endblock %}